# Generated by Django 5.2 on 2025-05-02 11:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='recipes', to=settings.AUTH_USER_MODEL),
        ),
    ]
